#!/usr/local/python3.7

from subprocess import PIPE, Popen


##main program bit 


def check_immut():
	p1=PIPE(["lsattr", "test_file"], stdout=PIPE)
	ou,err=p1.communicate()
	out=ou.decode('ascii').split( )
	
	with open('test_file', 'rt') as file_in:
		contents=file_in.read()
	
##flag_set ==> flag implies that the pre exiting restriction are already presnet. 

	if "Abuse..." in contents:
		flag_set=True
	else:
		flag_set=False

	if ("i" in out) or ("a" in out):
		if flag_set:
             		print("previosu restriction")
			flag_a=1
        	else:
             		print("immutables set, no abuse set, manual intervention")
			flag_proceed=0
	elsif flag_set:
		if ("i" in out) or ("a" in out):
			print("previosu restriction")
			flag_a=1
		else:
			print("Abuse set, no immutables set, manual intervention")
			flag_c=1
	else:
		print("No restictions")
		flag_d=1
     
	return flag_a, flag_b, flag_c, flag_d


		










	
